version: '3'

services:
  metrics:
    build: .
    hostname: clairesmetricshostname
    ports:
      - "8080:8080"
    env_file: github.env
    depends_on:
      - sql-server-db

  sql-server-db:
    container_name: comments-sql-db
    image: mysql:8.0.17
    ports:
      - "33061:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"